# Generated by Django 4.2.8 on 2023-12-27 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='nombre_heur',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='formation',
            name='objectif_du_cours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='prerequis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='profile_destine',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SeanceTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('confirmer_par_apprenant', models.BooleanField(default=False)),
                ('confirmer_par_instructeur', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_de_la_reunion', models.DateField()),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.formation')),
            ],
        ),
    ]
