# Generated by Django 4.2.8 on 2023-12-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0003_alter_formation_date_de_publication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cour',
            old_name='prix',
            new_name='montant',
        ),
        migrations.RemoveField(
            model_name='seancetravail',
            name='confirmer_par_apprenant',
        ),
        migrations.RemoveField(
            model_name='seancetravail',
            name='confirmer_par_instructeur',
        ),
    ]
