# Generated by Django 4.2.8 on 2024-01-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0005_chapitre_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='ordre',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
