# Generated by Django 4.2.8 on 2024-01-08 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formation', '0006_video_ordre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('duree', models.IntegerField()),
                ('point', models.IntegerField()),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Qcm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=2500)),
                ('description', models.TextField()),
                ('duree', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('point', models.IntegerField()),
                ('qcm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.qcm')),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.TextField()),
                ('correcte', models.BooleanField()),
                ('date', models.DateField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.question')),
            ],
        ),
        migrations.CreateModel(
            name='ResultatExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.examen')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.reponse')),
            ],
        ),
        migrations.AddField(
            model_name='examen',
            name='qcm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.qcm'),
        ),
    ]
