# Generated by Django 4.2.8 on 2024-01-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0008_seancetravail_confirmer_par_apprenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seancetravail',
            name='lien_de_la_reusion',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seancetravail',
            name='nom',
            field=models.CharField(max_length=512),
        ),
    ]
