# Generated by Django 4.2.8 on 2024-01-26 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0011_discution_envoyer_par_apprenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
