# Generated by Django 4.2.8 on 2024-03-02 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0013_suive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suive',
            name='formation',
        ),
        migrations.AddField(
            model_name='suive',
            name='souscategorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formation.souscategorie'),
            preserve_default=False,
        ),
    ]
