# Generated by Django 4.2.8 on 2024-03-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0014_remove_suive_formation_suive_souscategorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examen',
            name='reponse',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
