# Generated by Django 4.2.8 on 2024-03-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0016_participer'),
    ]

    operations = [
        migrations.AddField(
            model_name='participer',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
